<?php

declare(strict_types=1);

/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

return [
    'activation-error'        => 'Bannlyst, ugyldig token, eller konto allerede bekreftet!',
    'activation-success'      => 'Konto bekreftet! Du kan nå logge inn!',
    'add-image'               => 'Legg til bildelenke',
    'add-profile'             => 'Legg til profillenke',
    'allow-invite'            => 'Registrering er stengt! Du må bli invitert for å registrere deg! Du blir videresendt til innloggingssiden!',
    'allow-invite-appl'       => 'Registrering er stengt! Du må bli invitert for å registrere deg! Men du kan søke om medlemskap. Du blir sendt til søknadssiden.',
    'appl-closed'             => 'Søknader er stengt',
    'appl-intro'              => 'er en lukket side. Du må ha en invitasjonslenke for å registrere deg. Om du ikke har en slik lenke, så kan du søke om medlemskap.',
    'appl-reason'             => 'Hvor hørte du om ":sitename", og hvorfor vil du bli medlem?',
    'application'             => 'Søknad',
    'application-submitted'   => 'Din søknad er blitt sendt og du får snart svar på e-post!',
    'apply'                   => 'Apply',
    'are-you'                 => 'Er du:',
    'banned'                  => 'Denne kontoen er bannlyst!',
    'check-later'             => 'Sjekk igjen senere!',
    'code'                    => 'TOTP Code',
    'confirm-new-password'    => 'Confirm New Password',
    'confirm-password'        => 'Confirm Password',
    'delete-image'            => 'Slett siste bildelenke',
    'delete-profile'          => 'Slett siste profillenke',
    'email'                   => 'E-post',
    'email-verification-link' => 'An email verification link has been emailed to you!',
    'enter-recovery'          => 'Please enter one of the recovery codes provided to you when first enabling two-factor authentication.',
    'enter-totp'              => 'Please enter the 6-digit authentication code generated by your app.',
    'failed'                  => 'Brukernavn og/eller passord er feil.',
    'invalid-key'             => 'Feil eller for gammel invitasjon!',
    'login'                   => 'Logg inn',
    'login-now-on'            => 'Logger nå på',
    'logout'                  => 'Logg ut',
    'lost-password'           => 'Glemt passord?',
    'lost-username'           => 'Glemt brukernavn?',
    'need-invite'             => 'Åpen registrering er deaktivert og du må ha en invitasjon for å få tilgang!',
    'new-password'            => 'New Password',
    'newbie'                  => 'Nybegynner',
    'not-a-member'            => 'Ikke medlem? Registrer deg på under 30 sekunder.',
    'not-activated'           => 'Denne kontoen er enda ikke blitt aktivert og er enda i godkjenningsgruppen. Vennligst sjekk e-posten din for aktiveringslenken. Om du ikke mottok aktiveringskoden, vennligst klikk "glemt passord" og fullfør stegene der.',
    'password'                => 'Passord',
    'password-confirm-desc'   => 'Please confirm your password before proceeding.',
    'password-confirmation'   => 'Password confirmation',
    'password-reset'          => 'Reset Password',
    'proof-image'             => 'Bekreftelsesbilde URL',
    'proof-image-title'       => 'Lenker til profilskjermbilder',
    'proof-min'               => '(Minimum 2, Anbefalt 3)',
    'proof-profile'           => 'Profillenke URL',
    'proof-profile-title'     => 'Lenker til dine profiler',
    'recover-my-password'     => 'Tilbakestill mitt passord',
    'recovery-code'           => 'Recovery code',
    'register-thanks'         => 'Takk for at du ble med! Vennligst sjekk din e-post for å bekrefte din konto',
    'remember-me'             => 'Husk meg',
    'require-rules'           => 'Vennligst les og aksepter våre regler med å skrolle til bunnen av denne siden.',
    'send-verification-email' => 'Send Verification Email',
    'signup'                  => 'Registrer',
    'throttle'                => 'For mange forsøk. Prøv igjen om :seconds sekunder.',
    'totp-code'               => 'TOTP code',
    'unlock'                  => 'Lås opp',
    'user-icon'               => 'Brukerikon',
    'username'                => 'Brukernavn',
    'verify'                  => 'Verify',
    'verify-email'            => 'Verify Email',
    'verifying'               => 'Verifying...',
    'veteran'                 => 'Erfaring med private trackere',
    'welcome'                 => 'Velkommen tilbake!',
    'welcome-restore'         => 'Velkommen tilbake! Kontoen er ikke lenger deaktivert!'
];
