version: '3.4'

services:
  http:
    build:
      dockerfile: docker/nginx.Dockerfile
      context: .
      args:
        - APP_HOSTNAME=localhost
    environment:
      - NODE_ENV=production
    ports:
      - "8080:80"
    volumes:
      - public_files:/app/public/files
    depends_on:
      - app
    networks:
      - unit3d

  redis:
    image: redis:6-alpine
    networks:
      - unit3d

  mariadb:
    image: mariadb:10
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: unit3d
      MYSQL_DATABASE: unit3d
      MYSQL_USER: unit3d
      MYSQL_PASSWORD: unit3d
    networks:
      - unit3d

  echo-server:
    image: oanhnn/laravel-echo-server:latest
    container_name: unit3d-echo
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    networks:
      - unit3d

  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
    depends_on:
      - mariadb
      - redis
      - echo-server
    volumes:
      - composer_cache:/app/vendor
    restart: always
    networks:
      - unit3d

volumes:
  db_data: {}
  storage: {}
  public_files: {}
  composer_cache: {}

networks:
  unit3d:
    driver: bridge