version: '3.5'

services:
  frontend:
    build:
      dockerfile: docker/frontend.Dockerfile
      context: "."
    volumes:
      - public:/build/static
      - node_modules:/build/node_modules
    networks:
      - unit3d

  # Caddy based setup
  http:
    image: caddy/caddy:latest
    restart: always
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - public:/app/public
      - public_files:/app/public/files
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - unit3d

  redis:
    image: redis:6-alpine
    restart: always
    entrypoint: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - unit3d

  mariadb:
    image: mariadb:10
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: unit3d
    networks:
      - unit3d

  echo-server:
    image: oanhnn/laravel-echo-server:latest
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    networks:
      - unit3d

  portainer:
    image: portainer/portainer:latest
    restart: unless-stopped
    networks:
      - unit3d
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9009:9000"

  app:
    build:
      dockerfile: docker/Dockerfile
      context: ""
    restart: always
    tty: true
    depends_on:
      - mariadb
      - redis
      - echo-server
    volumes:
      - composer_cache:/app/vendor
      - storage:/app/storage
      - public:/app/public
      - public_files:/app/public/files
    networks:
      - unit3d

volumes:
  caddy_data:
  caddy_config:
  db_data:
  redis_data:
  storage:
  public_files:
  public:
  composer_cache:
  portainer_data:
  node_modules:

networks:
  unit3d:
    driver: bridge