<?php

declare(strict_types=1);

/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

return [
    'activation-error'        => 'Jste zabanován, neplatný link nebo máte účet již ověřen!',
    'activation-success'      => 'Účet byl aktivován! Nyní se můžete přihlásit!',
    'add-image'               => 'Přidejte jiný link obrázku',
    'add-profile'             => 'Přidejte jiný link profilu',
    'allow-invite'            => 'Registrace jsou uzavřeny! Musíte být pozván k registraci! Nyní budete přesměrování na přihlašovací stránku!',
    'allow-invite-appl'       => 'Registrace jsou uzavřeny! Musíte být pozván k registraci! Registrace aplikací je otevřena. Nyní budete přesměrování na aplikační stránku!',
    'appl-closed'             => 'Aplikace jsou uzavřeny',
    'appl-intro'              => 'je uzavřená komunita. Musíte mít pozvánku k registraci. Pokud jste pozvánku neobdrželi, můžete vyplnit následující žádost o členství.',
    'appl-reason'             => 'Jak jste se dozvěděli o ":sitename" a proč se chcete zapojit? ',
    'application'             => 'Aplikace',
    'application-submitted'   => 'Vaše žádost byla přijata. Brzy vás budeme emailem kontaktovat!',
    'apply'                   => 'Apply',
    'are-you'                 => 'Nacházíte se:',
    'banned'                  => 'Váš účet je zabanován!',
    'check-later'             => 'Zkontrolujte pozfději!',
    'code'                    => 'TOTP Code',
    'confirm-new-password'    => 'Confirm New Password',
    'confirm-password'        => 'Confirm Password',
    'delete-image'            => 'Smazat poslední link obrázku',
    'delete-profile'          => 'Smazat poslední link profilu',
    'email'                   => 'E-mail',
    'email-verification-link' => 'An email verification link has been emailed to you!',
    'enter-recovery'          => 'Please enter one of the recovery codes provided to you when first enabling two-factor authentication.',
    'enter-totp'              => 'Please enter the 6-digit authentication code generated by your app.',
    'failed'                  => 'Zadané udaje se neshodují s žádným účtem v systému.',
    'invalid-key'             => 'Pozvánka je neplatná nebo vypršela platnost!',
    'login'                   => 'Login',
    'login-now-on'            => 'Přihlaste se na',
    'logout'                  => 'Odhlásit',
    'lost-password'           => 'Zapomněl jste heslo?',
    'lost-username'           => 'Zapomněl jste nickname?',
    'need-invite'             => 'Registrace jsou zakázané, musíte byt pozván k získání přístupu!',
    'new-password'            => 'New Password',
    'newbie'                  => 'Nováček ve hře',
    'not-a-member'            => 'Ještě nejsi člen? Registrace netrvá déle než 30s.',
    'not-activated'           => 'Váš účet není stále aktivován. Prosím zkontrolujte si e-mail a aktivuje si účet pomocí aktivačniho linku. Pokud vám e-mail s aktivačním kódem nepřišel, klikni prosím na "Zapomněl jsem heslo" a řiďte se pokyny.',
    'password'                => 'Heslo',
    'password-confirm-desc'   => 'Please confirm your password before proceeding.',
    'password-confirmation'   => 'Password confirmation',
    'password-reset'          => 'Reset Password',
    'proof-image'             => 'Adresa URL důkazního snímku',
    'proof-image-title'       => 'Odkazy na snímky profilu',
    'proof-min'               => '(Minimálně 2, doporučené 3)',
    'proof-profile'           => 'Adresa URL odkazu na profil',
    'proof-profile-title'     => 'Odkazy na vaše profily',
    'recover-my-password'     => 'Obnovit mé heslo',
    'recovery-code'           => 'Recovery code',
    'register-thanks'         => 'Děkujeme za registraci! Prosím zkontrolujte svůj email kvůli aktivačnímu emailu',
    'remember-me'             => 'Zapamatovat',
    'require-rules'           => 'Přečtěte si prosím naše pravidla a přijměte je posunutím na konec stránky..',
    'send-verification-email' => 'Send Verification Email',
    'signup'                  => 'Registrovat',
    'throttle'                => 'Příliš mnoho pokusů. Prosim opakujte za :seconds vteřin.',
    'totp-code'               => 'TOTP code',
    'unlock'                  => 'Odemknout',
    'user-icon'               => 'Ikona uživatele',
    'username'                => 'Username',
    'verify'                  => 'Verify',
    'verify-email'            => 'Verify Email',
    'verifying'               => 'Verifying...',
    'veteran'                 => 'Zkušenosti se soukromými trackery',
    'welcome'                 => 'Vítej zpět!',
    'welcome-restore'         => 'Vítejte zpět! Váš účet již není deaktivován!'
];
