<?php

declare(strict_types=1);

/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

return [
    'activation-error'        => 'Verbannt, ungültiger Invite-Token oder das Nutzerkonto ist bereits aktiviert!',
    'activation-success'      => 'Nutzerkonto wurde aktiviert! Du kannst dich jetzt anmelden!',
    'add-image'               => 'Einen weiteres Bild hinzufügen',
    'add-profile'             => 'Einen weiteres Profil hinzufügen',
    'allow-invite'            => 'Registrierung ist geschlossen! Du musst eingeladen werden, um dich registrieren zu können! Du wurdest zur Anmeldeseite weitergeleitet!',
    'allow-invite-appl'       => 'Registrierung ist geschlossen, du kannst dich jedoch bewerben! Du wurdest zur Bewerbungsseite weitergeleitet!',
    'appl-closed'             => 'Bewerbungen sind geschlossen',
    'appl-intro'              => 'ist eine geschlossene Community. Du brauchst einen Invitelink, um dich registrieren zu können! Wenn du keinen Invite bekommen kannst, dann kannst du folgendes Bewerbungschreiben ausfüllen.',
    'appl-reason'             => 'Wie hast du von ":sitename" erfahren? Wieso willst du reinkommen? ',
    'application'             => 'Bewerbung',
    'application-submitted'   => 'Deine Bewerbung wurde abgeschickt. Du wirst demnächst eine E-Mail erhalten!',
    'apply'                   => 'Apply',
    'are-you'                 => 'Bist du:',
    'banned'                  => 'Dieser Account wurde gebannt!',
    'check-later'             => 'Komme später noch mal!',
    'code'                    => 'TOTP Code',
    'confirm-new-password'    => 'Confirm New Password',
    'confirm-password'        => 'Confirm Password',
    'delete-image'            => 'Letztes Bild löschen',
    'delete-profile'          => 'Letztes Profil löschen',
    'email'                   => 'E-Mail',
    'email-verification-link' => 'An email verification link has been emailed to you!',
    'enter-recovery'          => 'Please enter one of the recovery codes provided to you when first enabling two-factor authentication.',
    'enter-totp'              => 'Please enter the 6-digit authentication code generated by your app.',
    'failed'                  => 'Diese Anmeldedaten stimmen nicht mit unserer Datenbank überein.',
    'invalid-key'             => 'Ungültiger oder abgelaufener Invitelink!',
    'login'                   => 'Einloggen',
    'login-now-on'            => 'Jetzt einloggen auf',
    'logout'                  => 'Ausloggen',
    'lost-password'           => 'Passwort vergessen?',
    'lost-username'           => 'Nutzername vergessen?',
    'need-invite'             => 'Registrierung ist geschlossen, du brauchst einen Invite um Zugriff zu erhalten!',
    'new-password'            => 'New Password',
    'newbie'                  => 'Neu in der Szene?',
    'not-a-member'            => 'Noch kein Mitglied? Registriere dich in weniger als 30s.',
    'not-activated'           => 'Dieser Account wurde noch nicht aktiviert und befindet sich noch in der Validierungsgruppe. Bitte prüfe deinen E-Mail Postfach auf einen Aktivierungslink. Wenn du keinen Aktivierungslink erhalten hast, klicke bitte auf "Passwort vergessen" und führe die dortigen Schritte durch.',
    'password'                => 'Passwort',
    'password-confirm-desc'   => 'Please confirm your password before proceeding.',
    'password-confirmation'   => 'Password confirmation',
    'password-reset'          => 'Reset Password',
    'proof-image'             => 'Screenshot URL',
    'proof-image-title'       => 'Link zum Profil-Screenshot',
    'proof-min'               => '(Minimum 2, Empfohlen 3)',
    'proof-profile'           => 'Profil URL',
    'proof-profile-title'     => 'Link zum Profil auf anderem Tracker',
    'recover-my-password'     => 'Passwort zurücksetzen',
    'recovery-code'           => 'Recovery code',
    'register-thanks'         => 'Danke für die Registrierung! Bitte überprüfe dein E-Mail Postfach, um das Konto zu aktivieren.',
    'remember-me'             => 'Remember Me',
    'require-rules'           => 'Bitte lese und akzeptiere unsere Regeln, indem du zum Ende der Seite gehst.',
    'send-verification-email' => 'Send Verification Email',
    'signup'                  => 'Registrieren',
    'throttle'                => 'Zu viele Anmeldeversuche. Bitte versuche es erneut in :seconds Sekunden.',
    'totp-code'               => 'TOTP code',
    'unlock'                  => 'Entsperren',
    'user-icon'               => 'Nutzer Icon',
    'username'                => 'Nutzername',
    'verify'                  => 'Verify',
    'verify-email'            => 'Verify Email',
    'verifying'               => 'Verifying...',
    'veteran'                 => 'Erfahren mit Private Trackern?',
    'welcome'                 => 'Willkommen zurück!',
    'welcome-restore'         => 'Willkommen zurück! Dein Account ist nicht mehr deaktiviert!'
];
