<?php

declare(strict_types=1);

/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

return [
    'activation-error'        => 'Forbudt eller ugyldig token eller konto allerede bekræftet!',
    'activation-success'      => 'Konto bekræftet! Du kan nu logge ind!',
    'add-image'               => 'Tilføj endnu et billedlink',
    'add-profile'             => 'Tilføj endnu et profillink',
    'allow-invite'            => 'Åben registrering er lukket! Du skal inviteres for at kunne tilmelde dig! Du er blevet omdirigeret til login-siden!',
    'allow-invite-appl'       => 'Åben registrering er lukket! Du skal inviteres for at kunne tilmelde sig! Dog er tilmeldinger via ansøgninger åbne. Du er blevet omdirigeret til ansøgningsiden!',
    'appl-closed'             => 'Ansøgninger er lukket',
    'appl-intro'              => 'er et lukket fælleskab. Du skal have et invitationslink for at kunne registrere dig. Hvis du ikke kan få en invitation, kan du udfylde følgende ansøgning om medlemskab.',
    'appl-reason'             => 'Hvordan har du hørt om ":sitename" og hvorfor vil du gerne være medlem? ',
    'application'             => 'Ansøgning',
    'application-submitted'   => 'Din ansøgning er indsendt. Du modtager en e-mail når den er behandlet!',
    'apply'                   => 'Apply',
    'are-you'                 => 'Er du:',
    'banned'                  => 'Denne konto er udelukket!',
    'check-later'             => 'Kom tilbage senere!',
    'code'                    => 'TOTP Code',
    'confirm-new-password'    => 'Confirm New Password',
    'confirm-password'        => 'Confirm Password',
    'delete-image'            => 'Slet link til sidste billede',
    'delete-profile'          => 'Slet link til sidste profil',
    'email'                   => 'E-mail',
    'email-verification-link' => 'An email verification link has been emailed to you!',
    'enter-recovery'          => 'Please enter one of the recovery codes provided to you when first enabling two-factor authentication.',
    'enter-totp'              => 'Please enter the 6-digit authentication code generated by your app.',
    'failed'                  => 'Disse legitimationsoplysninger stemmer ikke overens med vores optegnelser.',
    'invalid-key'             => 'Ugyldig eller udløbet invitationsnøgle!',
    'login'                   => 'Logind',
    'login-now-on'            => 'Logind nu på',
    'logout'                  => 'Logud',
    'lost-password'           => 'Glemt din adgangskode?',
    'lost-username'           => 'Glemt dit brugernavn?',
    'need-invite'             => 'Åben registrering er deaktiveret, og du skal bruge en invitation for at få adgang!',
    'new-password'            => 'New Password',
    'newbie'                  => 'Ny i dette',
    'not-a-member'            => 'Ikke medlem? Tilmeld dig på under 30s.',
    'not-activated'           => 'Denne konto er ikke aktiveret og er stadig under validering. Tjek venligst din e-mail for aktiveringslink. Hvis du ikke modtog aktiveringskoden, skal du klikke på "glemt adgangskode" og udføre trinnene.',
    'password'                => 'Adgangskode',
    'password-confirm-desc'   => 'Please confirm your password before proceeding.',
    'password-confirmation'   => 'Password confirmation',
    'password-reset'          => 'Reset Password',
    'proof-image'             => 'Bevis billede URL',
    'proof-image-title'       => 'Links til profilskærmbilleder',
    'proof-min'               => '(Minimum 2, Anbefalet 3)',
    'proof-profile'           => 'Profil-link URL',
    'proof-profile-title'     => 'Links til dine profiler',
    'recover-my-password'     => 'Gendan min adgangskode',
    'recovery-code'           => 'Recovery code',
    'register-thanks'         => 'Tak for tilmeldingen! Tjek din e-mail for at validere din konto',
    'remember-me'             => 'Husk mig',
    'require-rules'           => 'Læs og accepter vores regler ved at rulle til bunden af siden.',
    'send-verification-email' => 'Send Verification Email',
    'signup'                  => 'Tilmeld',
    'throttle'                => 'For mange loginforsøg. Prøv igen om :seconds sekunder.',
    'totp-code'               => 'TOTP code',
    'unlock'                  => 'Lås op',
    'user-icon'               => 'Brugerikon',
    'username'                => 'Brugernavn',
    'verify'                  => 'Verify',
    'verify-email'            => 'Verify Email',
    'verifying'               => 'Verifying...',
    'veteran'                 => 'Erfaren med private trackere',
    'welcome'                 => 'Velkommen tilbage!',
    'welcome-restore'         => 'Velkommen tilbage! Din konto er ikke længere deaktiveret!'
];
