<?php

declare(strict_types=1);

/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

return [
    'activation-error'        => 'Λάθος συνδεσμος, ή λογαριασμός ηδη επιβεβαιωμένος!',
    'activation-success'      => 'Ο Λογαριασμός επιβεβαιώθηκε. Μπορείτε να εισέλθετε!',
    'add-image'               => 'Προσθηκη συνδέσμου φωτογραφιας',
    'add-profile'             => 'Προσθηκη συνδέσμου Profile',
    'allow-invite'            => 'Οι εγγραφές ειναι προς το παρόν κλειστές.! Πρέπει να έχετε πρόσκληση για να μπορέσετε να εγγραφείτε.! Σας μεταφέρουμε στη σελίδα εισόδου!',
    'allow-invite-appl'       => 'Οι εγγραφές ειναι προς το παρόν κλειστές.! Πρέπει να έχετε πρόσκληση για να μπορέσετε να εγγραφείτε.! Είναι ανοικτές όμως οι αιτήσεις.. Σας μεταφέρουμε στη σελίδα των αιτήσεων!',
    'appl-closed'             => 'Οι αιτήσεις είναι κλειστές',
    'appl-intro'              => 'είναι μια κλειστή κοινότητα.. Πρέπει να έχετε πρόσκληση για να μπορέσετε να εγγραφείτε.!. Αν δε μπορείτε να βρείτε πρόσκληση, μπορείτε να κάνετε αίτηση για εγγραφή.',
    'appl-reason'             => 'Πως μάθατε για το ":sitename" και γιατί θα πρεπει να σας δεχτούμε? ',
    'application'             => 'Αίτηση',
    'application-submitted'   => 'Η αίτηση σας καταχωρήθηκε. Θα λάβετε email συντομα!',
    'apply'                   => 'Apply',
    'are-you'                 => 'Are You:',
    'banned'                  => 'Αυός ο λογαριασμός έχει γινει BAN!',
    'check-later'             => 'Ελέγξτε πάλι αργότερα!',
    'code'                    => 'TOTP Code',
    'confirm-new-password'    => 'Confirm New Password',
    'confirm-password'        => 'Confirm Password',
    'delete-image'            => 'Διαγραφή τελευταίου συνδέσμου φωτογραφιας',
    'delete-profile'          => 'Διαγραφή τελευταίου συνδέσμου προφίλ',
    'email'                   => 'E-mail',
    'email-verification-link' => 'An email verification link has been emailed to you!',
    'enter-recovery'          => 'Please enter one of the recovery codes provided to you when first enabling two-factor authentication.',
    'enter-totp'              => 'Please enter the 6-digit authentication code generated by your app.',
    'failed'                  => 'Αυτά τα στοιχεία δεν αντιστοιχούν με τα δικά μας.',
    'invalid-key'             => 'Λανθασμένη ή Ληγμένη προσκληση!',
    'login'                   => 'Login',
    'login-now-on'            => 'Login now on',
    'logout'                  => 'Logout',
    'lost-password'           => 'Ξέχασες τον κωδικό σου?',
    'lost-username'           => 'Ξέχασες το ονομα χρήστη?',
    'need-invite'             => 'Οι εγγραφές ειναι προς το παρόν κλειστές. Πρέπει να έχετε πρόσκληση για να μπορέσετε να εγγραφείτε.!!',
    'new-password'            => 'New Password',
    'newbie'                  => 'Νέος στο χώρο',
    'not-a-member'            => 'Ακόμη να γίνεις μέλος? Κάνε εγγραφή Ντελόγω.',
    'not-activated'           => 'Αυτος ο Λογαριασμος δεν εχει επικυρωθει / επιβεβαιωθει και βρίσκεται ακόμα στο γκρουπ validating. Ελέγξτε το email σας για το σύνδεσμο ενεργοποίησης. Αν δεν έχετε λαβει τον κωδικο ενεργοποισης , παρακαλώ κάντε click "forgot password" και ακολουθήστε τα βήματα.',
    'password'                => 'Κωδικός',
    'password-confirm-desc'   => 'Please confirm your password before proceeding.',
    'password-confirmation'   => 'Password confirmation',
    'password-reset'          => 'Reset Password',
    'proof-image'             => 'Proof Image URL',
    'proof-image-title'       => 'Links to profile screenshots',
    'proof-min'               => '(Minimum 2, Recommended 3)',
    'proof-profile'           => 'Profile Link URL',
    'proof-profile-title'     => 'Links to your profiles',
    'recover-my-password'     => 'Ανάκτηση Κωδικού',
    'recovery-code'           => 'Recovery code',
    'register-thanks'         => 'Ευχαριτούμε για την εγγραφή! Ελέγξτε το email σας για να ενεργοποιήσετε το λογαριασμό σας',
    'remember-me'             => 'Να με θυμάσαι',
    'require-rules'           => 'Παρακαλούμε διαβάστε και αποδεχτείτε τους κανόνες λειτουργίας κατεβαίνοντας ως το τέλος της σελίδας.',
    'send-verification-email' => 'Send Verification Email',
    'signup'                  => 'Εγγραφή',
    'throttle'                => 'Πολλες Προσπάθειες σύνδεσης. Παρακαλώ δοκιμάστε ξανα σε :seconds δευτερόλεπτα.',
    'totp-code'               => 'TOTP code',
    'unlock'                  => 'Unlock',
    'user-icon'               => 'User Icon',
    'username'                => 'Ονομα χρηστη',
    'verify'                  => 'Verify',
    'verify-email'            => 'Verify Email',
    'verifying'               => 'Verifying...',
    'veteran'                 => 'Έμπειρος χρήστης σε ιδιωτικούς Trackers',
    'welcome'                 => 'Καλως ήρθες πάλι!',
    'welcome-restore'         => 'Καλως ήρθες πάλι! Ο Λογαριασμός σου , δεν είναι πλέον ανενεργός'
];
