<?php

declare(strict_types=1);

/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

return [
    'activation-error'        => 'O Token banido ou inválido ou a conta já foi confirmada!',
    'activation-success'      => 'Conta confirmada! Você já pode fazer o login!',
    'add-image'               => 'Adicionar outro link da imagem',
    'add-profile'             => 'Adicionar outro link de perfil',
    'allow-invite'            => 'Os registros estão fechados! Você deve ser convidado para se registrar! Você foi redirecionado para a página de Login!',
    'allow-invite-appl'       => 'Os registros estão fechados! Você deve ser convidado para se registrar! No entanto, as inscrições estão abertas. Você foi redirecionado para a página de inscrição!',
    'appl-closed'             => 'As inscrições estão fechadas',
    'appl-intro'              => 'é uma comunidade fechada. Você deve ter um link de convite para se registrar. Se você não conseguir um convite, você pode preencher o seguinte formulário de inscrição.',
    'appl-reason'             => 'Como você ficou sabendo do ":sitename" e por que você quer fazer parte dele? ',
    'application'             => 'Application',
    'application-submitted'   => 'A sua candidatura foi submetida. Você receberá um e-mail em breve!',
    'apply'                   => 'Apply',
    'are-you'                 => 'Você é:',
    'banned'                  => 'Essa conta foi banida!',
    'check-later'             => 'Verifique mais tarde!',
    'code'                    => 'TOTP Code',
    'confirm-new-password'    => 'Confirm New Password',
    'confirm-password'        => 'Confirm Password',
    'delete-image'            => 'Excluir o link da última imagem',
    'delete-profile'          => 'Excluir link do último perfil',
    'email'                   => 'E-mail',
    'email-verification-link' => 'An email verification link has been emailed to you!',
    'enter-recovery'          => 'Please enter one of the recovery codes provided to you when first enabling two-factor authentication.',
    'enter-totp'              => 'Please enter the 6-digit authentication code generated by your app.',
    'failed'                  => 'Essas credenciais não correspondem aos nossos registros.',
    'invalid-key'             => 'Chave de convite inválida ou expirada!',
    'login'                   => 'Login',
    'login-now-on'            => 'Iniciar sessão no',
    'logout'                  => 'Encerrar sessão',
    'lost-password'           => 'Esqueceu sua senha?',
    'lost-username'           => 'Esqueceu seu nome de usuário?',
    'need-invite'             => 'Os registros estão desativados e você precisará de um convite para ter acesso!',
    'new-password'            => 'New Password',
    'newbie'                  => 'Novo no jogo',
    'not-a-member'            => 'Ainda não é um membro? Registre-se em menos de 30 segundos.',
    'not-activated'           => 'Esta conta ainda não foi ativada e está em grupo de validação. Por favor, verifique o seu e-mail em busca de link de ativação. Se você não recebeu o código de ativação, clique em "Esqueci a senha" e complete os passos.',
    'password'                => 'Senha',
    'password-confirm-desc'   => 'Please confirm your password before proceeding.',
    'password-confirmation'   => 'Password confirmation',
    'password-reset'          => 'Reset Password',
    'proof-image'             => 'URL da imagem de prova',
    'proof-image-title'       => 'Links to profile screenshots',
    'proof-min'               => '(Mínimo 2, Recomendado 3)',
    'proof-profile'           => 'URL do link do perfil',
    'proof-profile-title'     => 'Links to your profiles',
    'recover-my-password'     => 'Recuperar minha senha',
    'recovery-code'           => 'Recovery code',
    'register-thanks'         => 'Obrigado por se registrar! Por favor, verifique o seu e-mail para confirmar sua conta',
    'remember-me'             => 'Lembrar',
    'require-rules'           => 'Por favor, leia e aceite as nossas regras rolando até ao final da página',
    'send-verification-email' => 'Send Verification Email',
    'signup'                  => 'Registre-se',
    'throttle'                => 'Demasiadas tentativas de login. Por favor, tente novamente em alguns segundos.',
    'totp-code'               => 'TOTP code',
    'unlock'                  => 'Desbloquear',
    'user-icon'               => 'Ícone do usuário',
    'username'                => 'Nome do usuário',
    'verify'                  => 'Verify',
    'verify-email'            => 'Verify Email',
    'verifying'               => 'Verifying...',
    'veteran'                 => 'Experiência com trackers privados',
    'welcome'                 => 'Bem-vindo(a) de volta!',
    'welcome-restore'         => 'Bem-vindo(a) de volta! A sua conta não está mais desativada!'
];
