<?php

declare(strict_types=1);

/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

return [
    'activation-error'        => 'Заблокований чи неправильний токен або обліковий запис вже підтверджено!',
    'activation-success'      => 'Реєстрація підтверджена! Тепер ви можете увійти',
    'add-image'               => 'Додати ще одне',
    'add-profile'             => 'Додати ще одне',
    'allow-invite'            => 'Відкрита реєстрація вимкнена! Ви повинні мати інвайт, щоб зареєструватись! Вас буде перенаправлено на сторінку входу!',
    'allow-invite-appl'       => 'Відкрита реєстрація вимкнена! Ви повинні мати інвайт, щоб зареєструватись! Але Ви можете створити заявку на реєстрацію. Вас буде перенаправлено на сторінку створення заявки!',
    'appl-closed'             => 'Заявки закриті',
    'appl-intro'              => 'це закрита спільнота. Тут Ви можете створити заявку на реєстрацію. Заповніть посилання на Ваш профіль на закритих трекерах. Чим більше Ви заповните інформації про себе, тим більша ймовірність, що Ваша заявка буде прийнята.',
    'appl-reason'             => 'Розкажіть трохи про себе. Звідки Ви дізнались про наш сайт?',
    'application'             => 'Заявка на реєстрацію',
    'application-submitted'   => 'Вашу заявку надіслано. Незабаром ви отримаєте електронний лист!',
    'apply'                   => 'Apply',
    'are-you'                 => 'Ви:',
    'banned'                  => 'Цей профіль заблоковано!',
    'check-later'             => 'Перевірте пізніше!',
    'code'                    => 'TOTP Code',
    'confirm-new-password'    => 'Confirm New Password',
    'confirm-password'        => 'Confirm Password',
    'delete-image'            => 'Видалити останнє',
    'delete-profile'          => 'Видалити останнє',
    'email'                   => 'E-mail',
    'email-verification-link' => 'An email verification link has been emailed to you!',
    'enter-recovery'          => 'Please enter one of the recovery codes provided to you when first enabling two-factor authentication.',
    'enter-totp'              => 'Please enter the 6-digit authentication code generated by your app.',
    'failed'                  => 'Ці облікові дані не збігаються з нашими записами.',
    'invalid-key'             => 'Недійсний або протермінований ключ інвайту!',
    'login'                   => 'Вхід',
    'login-now-on'            => 'Ввійти зараз',
    'logout'                  => 'Вийти',
    'lost-password'           => 'Забули Пароль?',
    'lost-username'           => 'Забули Логін?',
    'need-invite'             => 'Відкрита реєстрація вимкнена і вам потрібен інвайт, щоб отримати доступ!',
    'new-password'            => 'New Password',
    'newbie'                  => 'Новачок',
    'not-a-member'            => 'Ще не є учасником? Зареєструйтесь менше ніж за 30с.',
    'not-activated'           => 'Цей обліковий запис ще не був активований і знаходиться на перевірці. Будь ласка перевірте свою пошту на наявність активаційного посилання. Якщо Ви його не отримали, натисність "Забув пароль" і пройдіть наступні кроки.',
    'password'                => 'Пароль',
    'password-confirm-desc'   => 'Please confirm your password before proceeding.',
    'password-confirmation'   => 'Password confirmation',
    'password-reset'          => 'Reset Password',
    'proof-image'             => 'Посилання на скріншот профілю на трекері',
    'proof-image-title'       => 'Посилання на скріншоти Ваших профілів на інших торрент трекерах, пріоритет надається закритим трекерам',
    'proof-min'               => '(Мінімум 2)',
    'proof-profile'           => 'Посилання на Ваш профіль на трекері',
    'proof-profile-title'     => 'Посилання на Ваші профілі на інших торрент трекерах, пріоритет надається закритим трекерам',
    'recover-my-password'     => 'Відновити Мій Пароль',
    'recovery-code'           => 'Recovery code',
    'register-thanks'         => 'Дякуємо за реєстрацію! Будь ласка, перевірте свою електронну пошту, щоб підтвердити свій обліковий запис',
    'remember-me'             => 'Запам\'ятати',
    'require-rules'           => 'Будь ласка, прочитайте та прийміть наші правила, прокрутивши сторінку донизу.',
    'send-verification-email' => 'Send Verification Email',
    'signup'                  => 'Реєстрація',
    'throttle'                => 'Занадто багато спроб входу. Будь ласка, спробуйте ще раз, через :seconds секунд.',
    'totp-code'               => 'TOTP code',
    'unlock'                  => 'Розблокувати',
    'user-icon'               => 'Піктограма',
    'username'                => 'Логін',
    'verify'                  => 'Verify',
    'verify-email'            => 'Verify Email',
    'verifying'               => 'Verifying...',
    'veteran'                 => 'Маєте досвід користування закритими торрент трекерами',
    'welcome'                 => 'З Поверненням!',
    'welcome-restore'         => 'З Поверненням! Ваш Профіль Знову Активний!'
];
