<?php

declare(strict_types=1);

/**
 * NOTICE OF LICENSE.
 *
 * UNIT3D Community Edition is open-sourced software licensed under the GNU Affero General Public License v3.0
 * The details is bundled with this project in the file LICENSE.txt.
 *
 * @project    UNIT3D Community Edition
 *
 * @author     HDVinnie <hdinnovations@protonmail.com>
 * @license    https://www.gnu.org/licenses/agpl-3.0.en.html/ GNU Affero General Public License v3.0
 */

use App\Enums\ModerationStatus;
use App\Http\Controllers\Staff\ModerationController;
use App\Http\Requests\Staff\UpdateModerationRequest;
use App\Http\Middleware\UpdateLastAction;
use App\Models\Torrent;
use App\Models\User;
use Illuminate\Routing\Middleware\ThrottleRequestsWithRedis;
use Illuminate\Support\Facades\Notification;

test('index returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $torrents = Torrent::factory()->times(3)->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->get(route('staff.moderation.index'));

    $response->assertOk();
    $response->assertViewIs('Staff.moderation.index');
    $response->assertViewHas('current');
    $response->assertViewHas('pending');
    $response->assertViewHas('postponed');
    $response->assertViewHas('rejected');

    // TODO: perform additional assertions
});

test('update validates with a form request', function (): void {
    $this->assertActionUsesFormRequest(
        ModerationController::class,
        'update',
        UpdateModerationRequest::class
    );
});

test('destroy rejected deletes selected rejected torrents', function (): void {
    $this->withoutMiddleware(ThrottleRequestsWithRedis::class);
    $this->withoutMiddleware(UpdateLastAction::class);

    Notification::fake();

    $user = auth()->user();
    $user->group->update(['is_torrent_modo' => true]);
    $user->load('group');

    $selected = Torrent::factory()->count(2)->create([
        'status' => ModerationStatus::REJECTED,
    ]);
    $unselected = Torrent::factory()->create([
        'status' => ModerationStatus::REJECTED,
    ]);

    $response = $this->delete(route('staff.moderation.destroy_rejected'), [
        'torrent_ids' => $selected->pluck('id')->all(),
        'message'     => 'Clearing old rejected uploads.',
    ]);

    $response->assertRedirect(route('staff.moderation.index'));
    $response->assertSessionHas('success');

    foreach ($selected as $torrent) {
        $this->assertSoftDeleted('torrents', ['id' => $torrent->id]);
    }

    $this->assertNotSoftDeleted('torrents', ['id' => $unselected->id]);
});

test('destroy rejected refuses non rejected selections', function (): void {
    $this->withoutMiddleware(ThrottleRequestsWithRedis::class);
    $this->withoutMiddleware(UpdateLastAction::class);

    Notification::fake();

    $user = auth()->user();
    $user->group->update(['is_torrent_modo' => true]);
    $user->load('group');

    $rejected = Torrent::factory()->create([
        'status' => ModerationStatus::REJECTED,
    ]);
    $pending = Torrent::factory()->create([
        'status' => ModerationStatus::PENDING,
    ]);

    $response = $this->delete(route('staff.moderation.destroy_rejected'), [
        'torrent_ids' => [$rejected->id, $pending->id],
        'message'     => 'Clearing old rejected uploads.',
    ]);

    $response->assertRedirect(route('staff.moderation.index'));
    $response->assertSessionHasErrors();

    $this->assertNotSoftDeleted('torrents', ['id' => $rejected->id]);
    $this->assertNotSoftDeleted('torrents', ['id' => $pending->id]);
});

test('update returns an ok response', function (): void {
    $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

    $torrent = Torrent::factory()->create();
    $user = User::factory()->create();

    $response = $this->actingAs($user)->post(route('staff.moderation.update', ['id' => $id]), [
        // TODO: send request data
    ]);

    $response->assertOk();

    // TODO: perform additional assertions
});

// test cases...
