name: Translation Coverage Check
on: [ pull_request ]
jobs:
    translation-check:
        strategy:
            matrix:
                operating-system:
                    - ubuntu-22.04
                php-version:
                    - '8.4'
        name: php ${{ matrix.php-version }} on ${{ matrix.operating-system }}
        runs-on: ${{ matrix.operating-system }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
                with:
                    fetch-depth: 0  # Fetch all history for comparing with base branch
            -   name: Setup PHP ${{ matrix.php-version }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: curl, dom, gd, libxml, mbstring, zip, mysql, xml, intl, bcmath, redis-phpredis/phpredis@6.0.1
                    ini-values: error_reporting=E_ALL
                    coverage: none
                    tools: composer:v2
                env:
                    REDIS_CONFIGURE_OPTS: --enable-redis
            -   name: Prepare The Laravel Environment
                run: cp .env.example .env
            -   name: Install Composer Dependencies
                env:
                    COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
                run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
            -   name: Generate Application Key
                run: php artisan key:generate
            -   name: Clear Application Cache
                run: php artisan clear:all_cache
            -   name: Get current translation coverage
                id: current-coverage
                run: |
                    php artisan translations:manage report --show-extra --markdown > /dev/null
                    echo "current_coverage=$(grep -oP '(?<=Coverage \| )[0-9.]+(?=%)' docs/translation-report-*.md | awk '{sum+=$1; count+=1} END {print sum/count}')" >> $GITHUB_OUTPUT
            -   name: Detect hardcoded strings
                id: hardcoded
                run: |
                    php artisan translations:manage report-hardcoded --markdown
                    echo "hardcoded_count=$(grep -oP '(?<=Total hardcoded strings found \| )[0-9]+' docs/hardcoded-strings-report.md)" >> $GITHUB_OUTPUT
            -   name: Check translation coverage history
                id: coverage-history
                run: |
                    # Get the base branch of the PR
                    BASE_BRANCH=${{ github.base_ref }}

                    # Checkout the base branch to run the coverage check
                    git checkout $BASE_BRANCH
                    composer install --no-interaction --prefer-dist --no-progress
                    php artisan translations:manage report --markdown > /dev/null

                    # Get the previous coverage
                    PREV_COVERAGE=$(grep -oP '(?<=Coverage \| )[0-9.]+(?=%)' docs/translation-report-*.md | awk '{sum+=$1; count+=1} END {print sum/count}')
                    echo "previous_coverage=$PREV_COVERAGE" >> $GITHUB_OUTPUT

                    # Go back to the PR branch
                    git checkout FETCH_HEAD
            -   name: Generate PR comment
                id: generate-comment
                run: |
                    CURRENT=$(echo "${{ steps.current-coverage.outputs.current_coverage }}" | xargs printf "%.2f")
                    PREVIOUS=$(echo "${{ steps.coverage-history.outputs.previous_coverage }}" | xargs printf "%.2f")
                    HARDCODED=${{ steps.hardcoded.outputs.hardcoded_count }}

                    # Calculate difference
                    DIFF=$(echo "$CURRENT - $PREVIOUS" | bc)

                    if (( $(echo "$DIFF >= 0" | bc -l) )); then
                      CHANGE_ICON="🔼"
                      CHANGE_COLOR="green"
                    else
                      CHANGE_ICON="🔽"
                      CHANGE_COLOR="red"
                    fi

                    cat > comment.md << EOF
                    ## Translation Coverage Report

                    | Metric | Value |
                    | --- | --- |
                    | Current Coverage | $CURRENT% |
                    | Previous Coverage | $PREVIOUS% |
                    | Change | <span style="color:$CHANGE_COLOR">$CHANGE_ICON $DIFF%</span> |
                    | Hardcoded Strings | $HARDCODED |

                    EOF
            -   name: Comment PR
                uses: actions/github-script@v7
                with:
                    github-token: ${{ secrets.UNIT3D_BOT_TOKEN }}
                    script: |
                        const fs = require('fs');
                        const commentBody = fs.readFileSync('comment.md', 'utf8');
                        const { owner, repo, number } = context.issue;
                        const number = github.context.payload.pull_request.number;

                        // First check if the bot already commented
                        const comments = await github.rest.issues.listComments({
                          owner,
                          repo,
                          issue_number: number
                        });

                        const botComment = comments.data.find(comment =>
                          comment.user.login === 'unit3d-bot' &&
                          comment.body.includes('Translation Coverage Report')
                        );

                        if (botComment) {
                          // Update existing comment
                          await github.rest.issues.updateComment({
                            owner,
                            repo,
                            comment_id: botComment.id,
                            body: commentBody
                          });
                        } else {
                          // Create new comment
                          await github.rest.issues.createComment({
                            owner,
                            repo,
                            issue_number: number,
                            body: commentBody
                          });
                        }
            -   name: Check if coverage is decreasing
                if: ${{ steps.current-coverage.outputs.current_coverage < steps.coverage-history.outputs.previous_coverage }}
                run: |
                    echo "🚨 Translation coverage is decreasing from ${{ steps.coverage-history.outputs.previous_coverage }}% to ${{ steps.current-coverage.outputs.current_coverage }}%"
                    exit 1
            -   name: Check if full coverage with hardcoded strings
                if: ${{ steps.current-coverage.outputs.current_coverage >= 100 && steps.hardcoded.outputs.hardcoded_count > 0 }}
                run: |
                    echo "🚨 You have achieved 100% translation coverage but still have ${{ steps.hardcoded.outputs.hardcoded_count }} hardcoded strings"
                    exit 1
