name: Laravel IDE Helper
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        operating-system:
          - ubuntu-22.04
        php-version:
          - '8.3'
    name: php ${{ matrix.php-version }} on ${{ matrix.operating-system }}
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: unit3d
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:7.2.1
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: bcmath, ctype, dom, fileinfo, json, libxml, mbstring, openssl, pdo, tokenizer, xml, zip
          coverage: none
      - name: Install Composer Dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Prepare The Laravel Environment
        run: cp .env.example .env
      - name: Generate Application Key
        run: php artisan key:generate
      - name: Run Migrations
        run: php artisan migrate --force
      - name: Clear Application Cache
        run: php artisan optimize:clear
      - name: Run Laravel IDE Helper
        run: php artisan ide-helper:models --write --reset
      - name: Run Pint
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: psr12
          verboseMode: true
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update model docblocks (Laravel IDE Helper CI)
          commit_user_name: HDVinne
          commit_user_email: hdinnovations@protonmail.com
          commit_author: HDVinnie <hdinnovations@protonmail.com>