name: PHP Lint (Pint)
on: [push, pull_request]
jobs:
  phplint:
    strategy:
      matrix:
        operating-system:
          - ubuntu-22.04
    name: ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Composer Dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
      - name: Run Pint
        run: ./vendor/bin/pint
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: PHP Style Change (Laravel Pint CI)
          commit_user_name: HDVinne
          commit_user_email: hdinnovations@protonmail.com
          commit_author: HDVinnie <hdinnovations@protonmail.com>
